import React, { useState } from 'react';
import { useAuth } from '../../context/AuthContext';
import { InterviewType, DifficultyLevel } from '../../types';
import { ROLE_TAXONOMY } from '../../data/initialData';
import { X, Sparkles, Briefcase, Brain, Users, Code, FileText, ArrowRight } from 'lucide-react';

interface InterviewSetupModalProps {
  isOpen: boolean;
  onClose: () => void;
  onStart: (config: {
    type: InterviewType;
    difficulty: DifficultyLevel;
    questionCount: number;
    targetRole: string;
    useResume: boolean;
  }) => void;
}

export const InterviewSetupModal: React.FC<InterviewSetupModalProps> = ({ isOpen, onClose, onStart }) => {
  const { profile } = useAuth();

  const [type, setType] = useState<InterviewType>('mixed');
  const [difficulty, setDifficulty] = useState<DifficultyLevel>('intermediate');
  const [questionCount, setQuestionCount] = useState<number>(5);
  const [targetRole, setTargetRole] = useState<string>(profile.career?.targetRole || 'Full Stack Developer');
  const [useResume, setUseResume] = useState<boolean>(!!profile.resume);

  if (!isOpen) return null;

  const interviewTypes = [
    {
      id: 'technical' as InterviewType,
      title: 'Technical Fundamentals',
      desc: 'OOP, data structures, databases, API design, & frameworks',
      icon: Brain,
    },
    {
      id: 'hr' as InterviewType,
      title: 'HR & Behavioral',
      desc: 'STAR method, conflict resolution, situational reasoning',
      icon: Users,
    },
    {
      id: 'mixed' as InterviewType,
      title: 'Full Placement Mock',
      desc: 'Complete technical screening plus behavioral cross-examination',
      icon: Sparkles,
    },
    {
      id: 'resume' as InterviewType,
      title: 'Resume Project Defense',
      desc: 'Defend your actual projects, stacks, and architecture choices',
      icon: FileText,
    },
  ];

  const targetRoles = Object.keys(ROLE_TAXONOMY);

  const handleLaunch = () => {
    onStart({
      type,
      difficulty,
      questionCount,
      targetRole,
      useResume,
    });
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/70 backdrop-blur-xs animate-in fade-in">
      <div className="relative w-full max-w-xl bg-white dark:bg-slate-900 rounded-2xl shadow-xl border border-slate-200 dark:border-slate-800 p-6 sm:p-7 max-h-[90vh] overflow-y-auto depth-surface">
        
        <button
          onClick={onClose}
          className="absolute top-4 right-4 p-1.5 rounded-lg text-slate-400 hover:text-slate-700 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-800 transition"
        >
          <X className="w-4 h-4" />
        </button>

        <div className="mb-5 pb-3 border-b border-slate-100 dark:border-slate-800">
          <h3 className="text-lg font-bold tracking-tight text-slate-900 dark:text-white">
            Configure AI Mock Interview
          </h3>
          <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
            Questions will be dynamically generated by Gemini AI matching your target role.
          </p>
        </div>

        <div className="space-y-5">
          
          {/* 1. Interview Round Type */}
          <div>
            <label className="block text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-2">
              1. Interview Round
            </label>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
              {interviewTypes.map((item) => {
                const Icon = item.icon;
                const isSelected = type === item.id;
                return (
                  <button
                    key={item.id}
                    type="button"
                    onClick={() => setType(item.id)}
                    className={`p-3.5 rounded-xl border text-left flex items-start space-x-3 transition btn-tactile ${
                      isSelected
                        ? 'border-slate-900 dark:border-slate-100 bg-slate-50 dark:bg-slate-800/80 shadow-xs'
                        : 'border-slate-200 dark:border-slate-800 hover:border-slate-300 dark:hover:border-slate-700'
                    }`}
                  >
                    <div className="w-8 h-8 rounded-lg bg-slate-100 dark:bg-slate-800 flex items-center justify-center text-slate-700 dark:text-slate-300 shrink-0 mt-0.5">
                      <Icon className="w-4 h-4" />
                    </div>
                    <div>
                      <h4 className="text-xs font-bold text-slate-900 dark:text-white">{item.title}</h4>
                      <p className="text-[11px] text-slate-500 dark:text-slate-400 mt-0.5 line-clamp-2 leading-relaxed">
                        {item.desc}
                      </p>
                    </div>
                  </button>
                );
              })}
            </div>
          </div>

          {/* 2. Target Role & Difficulty */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-1.5">
                2. Target Role
              </label>
              <div className="relative">
                <select
                  value={targetRole}
                  onChange={(e) => setTargetRole(e.target.value)}
                  className="w-full px-3 py-2 rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-900 dark:text-white text-xs font-medium focus:outline-none focus:ring-1 focus:ring-slate-900 dark:focus:ring-slate-100"
                >
                  {targetRoles.map((r) => (
                    <option key={r} value={r}>{r}</option>
                  ))}
                </select>
              </div>
            </div>

            <div>
              <label className="block text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-1.5">
                3. Difficulty
              </label>
              <div className="grid grid-cols-3 gap-1 p-0.5 bg-slate-100 dark:bg-slate-800 rounded-lg">
                {(['beginner', 'intermediate', 'advanced'] as DifficultyLevel[]).map((d) => (
                  <button
                    key={d}
                    type="button"
                    onClick={() => setDifficulty(d)}
                    className={`py-1.5 text-xs font-semibold rounded-md capitalize transition ${
                      difficulty === d
                        ? 'bg-white dark:bg-slate-900 text-slate-900 dark:text-white shadow-xs'
                        : 'text-slate-500 hover:text-slate-900 dark:hover:text-white'
                    }`}
                  >
                    {d}
                  </button>
                ))}
              </div>
            </div>
          </div>

          {/* 3. Number of Questions */}
          <div>
            <div className="flex items-center justify-between mb-1.5">
              <label className="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">
                4. Session Length
              </label>
              <span className="text-xs text-slate-500 dark:text-slate-400 font-mono tabular-nums">
                {questionCount} Questions (~{questionCount * 3} mins)
              </span>
            </div>
            <div className="grid grid-cols-3 gap-2">
              {[3, 5, 8].map((cnt) => (
                <button
                  key={cnt}
                  type="button"
                  onClick={() => setQuestionCount(cnt)}
                  className={`py-2 rounded-lg border text-xs font-bold transition btn-tactile ${
                    questionCount === cnt
                      ? 'border-slate-900 dark:border-slate-100 bg-slate-900 text-white dark:bg-slate-100 dark:text-slate-900 shadow-xs'
                      : 'border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-800'
                  }`}
                >
                  {cnt} Questions
                </button>
              ))}
            </div>
          </div>

          {/* Resume Option */}
          {profile.resume && (
            <div className="p-3 rounded-lg border border-slate-200 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-800/40 flex items-center justify-between text-xs">
              <div>
                <p className="font-semibold text-slate-900 dark:text-white">
                  Include Resume Defense Questions
                </p>
                <p className="text-[11px] text-slate-500 dark:text-slate-400">
                  Using parsed resume: {profile.resume.fileName}
                </p>
              </div>
              <input
                type="checkbox"
                checked={useResume}
                onChange={(e) => setUseResume(e.target.checked)}
                className="w-4 h-4 rounded text-slate-900 dark:text-slate-100 focus:ring-slate-900 cursor-pointer"
              />
            </div>
          )}

          {/* Launch Button */}
          <button
            type="button"
            onClick={handleLaunch}
            className="w-full py-3 px-6 rounded-xl bg-slate-900 hover:bg-slate-800 dark:bg-slate-100 dark:hover:bg-slate-200 text-white dark:text-slate-900 font-bold text-xs shadow-md transition flex items-center justify-center space-x-2 btn-tactile mt-2"
          >
            <span>Launch Mock Interview Room</span>
            <ArrowRight className="w-4 h-4" />
          </button>
        </div>
      </div>
    </div>
  );
};
